// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.azotov.roo.model;

import com.azotov.roo.model.Branch;
import com.azotov.roo.model.Merchant;

privileged aspect Branch_Roo_JavaBean {
    
    public String Branch.getAddress() {
        return this.Address;
    }
    
    public void Branch.setAddress(String Address) {
        this.Address = Address;
    }
    
    public String Branch.getName() {
        return this.Name;
    }
    
    public void Branch.setName(String Name) {
        this.Name = Name;
    }
    
    public Merchant Branch.getMerchant() {
        return this.Merchant;
    }
    
    public void Branch.setMerchant(Merchant Merchant) {
        this.Merchant = Merchant;
    }
    
}
