// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.azotov.roo.model;

import com.azotov.roo.model.Branch;
import flexjson.JSONDeserializer;
import flexjson.JSONSerializer;
import java.util.ArrayList;
import java.util.Collection;
import java.util.List;

privileged aspect Branch_Roo_Json {
    
    public String Branch.toJson() {
        return new JSONSerializer()
        .exclude("*.class").deepSerialize(this);
    }
    
    public String Branch.toJson(String[] fields) {
        return new JSONSerializer()
        .include(fields).exclude("*.class").deepSerialize(this);
    }
    
    public static Branch Branch.fromJsonToBranch(String json) {
        return new JSONDeserializer<Branch>()
        .use(null, Branch.class).deserialize(json);
    }
    
    public static String Branch.toJsonArray(Collection<Branch> collection) {
        return new JSONSerializer()
        .exclude("*.class").deepSerialize(collection);
    }
    
    public static String Branch.toJsonArray(Collection<Branch> collection, String[] fields) {
        return new JSONSerializer()
        .include(fields).exclude("*.class").deepSerialize(collection);
    }
    
    public static Collection<Branch> Branch.fromJsonArrayToBranches(String json) {
        return new JSONDeserializer<List<Branch>>()
        .use("values", Branch.class).deserialize(json);
    }
    
}
