// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.azotov.roo.model;

import com.azotov.roo.model.Configuration;
import flexjson.JSONDeserializer;
import flexjson.JSONSerializer;
import java.util.ArrayList;
import java.util.Collection;
import java.util.List;

privileged aspect Configuration_Roo_Json {
    
    public String Configuration.toJson() {
        return new JSONSerializer()
        .exclude("*.class").deepSerialize(this);
    }
    
    public String Configuration.toJson(String[] fields) {
        return new JSONSerializer()
        .include(fields).exclude("*.class").deepSerialize(this);
    }
    
    public static Configuration Configuration.fromJsonToConfiguration(String json) {
        return new JSONDeserializer<Configuration>()
        .use(null, Configuration.class).deserialize(json);
    }
    
    public static String Configuration.toJsonArray(Collection<Configuration> collection) {
        return new JSONSerializer()
        .exclude("*.class").deepSerialize(collection);
    }
    
    public static String Configuration.toJsonArray(Collection<Configuration> collection, String[] fields) {
        return new JSONSerializer()
        .include(fields).exclude("*.class").deepSerialize(collection);
    }
    
    public static Collection<Configuration> Configuration.fromJsonArrayToConfigurations(String json) {
        return new JSONDeserializer<List<Configuration>>()
        .use("values", Configuration.class).deserialize(json);
    }
    
}
