// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.azotov.roo.model;

import com.azotov.roo.model.Configuration;

privileged aspect Configuration_Roo_JavaBean {
    
    public String Configuration.getName() {
        return this.name;
    }
    
    public void Configuration.setName(String name) {
        this.name = name;
    }
    
    public Double Configuration.getRate() {
        return this.Rate;
    }
    
    public void Configuration.setRate(Double Rate) {
        this.Rate = Rate;
    }
    
}
