// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.azotov.roo.model;

import com.azotov.roo.model.EndUser;

privileged aspect EndUser_Roo_JavaBean {
    
    public String EndUser.getName() {
        return this.Name;
    }
    
    public void EndUser.setName(String Name) {
        this.Name = Name;
    }
    
    public Long EndUser.getUserNo() {
        return this.UserNo;
    }
    
    public void EndUser.setUserNo(Long UserNo) {
        this.UserNo = UserNo;
    }
    
}
