// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.azotov.roo.model;

import com.azotov.roo.model.IssuerAgent;
import flexjson.JSONDeserializer;
import flexjson.JSONSerializer;
import java.util.ArrayList;
import java.util.Collection;
import java.util.List;

privileged aspect IssuerAgent_Roo_Json {
    
    public String IssuerAgent.toJson() {
        return new JSONSerializer()
        .exclude("*.class").deepSerialize(this);
    }
    
    public String IssuerAgent.toJson(String[] fields) {
        return new JSONSerializer()
        .include(fields).exclude("*.class").deepSerialize(this);
    }
    
    public static IssuerAgent IssuerAgent.fromJsonToIssuerAgent(String json) {
        return new JSONDeserializer<IssuerAgent>()
        .use(null, IssuerAgent.class).deserialize(json);
    }
    
    public static String IssuerAgent.toJsonArray(Collection<IssuerAgent> collection) {
        return new JSONSerializer()
        .exclude("*.class").deepSerialize(collection);
    }
    
    public static String IssuerAgent.toJsonArray(Collection<IssuerAgent> collection, String[] fields) {
        return new JSONSerializer()
        .include(fields).exclude("*.class").deepSerialize(collection);
    }
    
    public static Collection<IssuerAgent> IssuerAgent.fromJsonArrayToIssuerAgents(String json) {
        return new JSONDeserializer<List<IssuerAgent>>()
        .use("values", IssuerAgent.class).deserialize(json);
    }
    
}
