// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.azotov.roo.model;

import com.azotov.roo.model.Issuer;
import com.azotov.roo.model.IssuerAgent;
import java.util.Set;

privileged aspect IssuerAgent_Roo_JavaBean {
    
    public String IssuerAgent.getName() {
        return this.Name;
    }
    
    public void IssuerAgent.setName(String Name) {
        this.Name = Name;
    }
    
    public Set<Issuer> IssuerAgent.getIssuers() {
        return this.Issuers;
    }
    
    public void IssuerAgent.setIssuers(Set<Issuer> Issuers) {
        this.Issuers = Issuers;
    }
    
}
