// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.azotov.roo.model;

import com.azotov.roo.model.Issuer;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Version;

privileged aspect Issuer_Roo_Jpa_Entity {
    
    declare @type: Issuer: @Entity;
    
    @Id
    @GeneratedValue(strategy = GenerationType.AUTO)
    @Column(name = "id")
    private Long Issuer.id;
    
    @Version
    @Column(name = "version")
    private Integer Issuer.version;
    
    public Long Issuer.getId() {
        return this.id;
    }
    
    public void Issuer.setId(Long id) {
        this.id = id;
    }
    
    public Integer Issuer.getVersion() {
        return this.version;
    }
    
    public void Issuer.setVersion(Integer version) {
        this.version = version;
    }
    
}
