// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.azotov.roo.model;

import com.azotov.roo.model.Issuer;
import flexjson.JSONDeserializer;
import flexjson.JSONSerializer;
import java.util.ArrayList;
import java.util.Collection;
import java.util.List;

privileged aspect Issuer_Roo_Json {
    
    public String Issuer.toJson() {
        return new JSONSerializer()
        .exclude("*.class").deepSerialize(this);
    }
    
    public String Issuer.toJson(String[] fields) {
        return new JSONSerializer()
        .include(fields).exclude("*.class").deepSerialize(this);
    }
    
    public static Issuer Issuer.fromJsonToIssuer(String json) {
        return new JSONDeserializer<Issuer>()
        .use(null, Issuer.class).deserialize(json);
    }
    
    public static String Issuer.toJsonArray(Collection<Issuer> collection) {
        return new JSONSerializer()
        .exclude("*.class").deepSerialize(collection);
    }
    
    public static String Issuer.toJsonArray(Collection<Issuer> collection, String[] fields) {
        return new JSONSerializer()
        .include(fields).exclude("*.class").deepSerialize(collection);
    }
    
    public static Collection<Issuer> Issuer.fromJsonArrayToIssuers(String json) {
        return new JSONDeserializer<List<Issuer>>()
        .use("values", Issuer.class).deserialize(json);
    }
    
}
