// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.azotov.roo.model;

import com.azotov.roo.model.Issuer;

privileged aspect Issuer_Roo_JavaBean {
    
    public String Issuer.getName() {
        return this.Name;
    }
    
    public void Issuer.setName(String Name) {
        this.Name = Name;
    }
    
    public Double Issuer.getRate() {
        return this.Rate;
    }
    
    public void Issuer.setRate(Double Rate) {
        this.Rate = Rate;
    }
    
}
