// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.azotov.roo.model;

import com.azotov.roo.model.Merchant;
import java.util.List;
import javax.persistence.EntityManager;
import javax.persistence.PersistenceContext;
import org.springframework.transaction.annotation.Transactional;

privileged aspect Merchant_Roo_Jpa_ActiveRecord {
    
    @PersistenceContext
    transient EntityManager Merchant.entityManager;
    
    public static final List<String> Merchant.fieldNames4OrderClauseFilter = java.util.Arrays.asList("Name", "CompanyName", "CompanyRegisterNumber", "BusinessNature", "BusinessRegisterDocument", "ContactPerson", "Address", "Contact", "Email", "BillingCycle", "AccountNumber", "DateJoin", "NextBillingDate", "Remarks", "Rate", "Terminals", "Branches", "IssuerAgent");
    
    public static final EntityManager Merchant.entityManager() {
        EntityManager em = new Merchant().entityManager;
        if (em == null) throw new IllegalStateException("Entity manager has not been injected (is the Spring Aspects JAR configured as an AJC/AJDT aspects library?)");
        return em;
    }
    
    public static long Merchant.countMerchants() {
        return entityManager().createQuery("SELECT COUNT(o) FROM Merchant o", Long.class).getSingleResult();
    }
    
    public static List<Merchant> Merchant.findAllMerchants() {
        return entityManager().createQuery("SELECT o FROM Merchant o", Merchant.class).getResultList();
    }
    
    public static List<Merchant> Merchant.findAllMerchants(String sortFieldName, String sortOrder) {
        String jpaQuery = "SELECT o FROM Merchant o";
        if (fieldNames4OrderClauseFilter.contains(sortFieldName)) {
            jpaQuery = jpaQuery + " ORDER BY " + sortFieldName;
            if ("ASC".equalsIgnoreCase(sortOrder) || "DESC".equalsIgnoreCase(sortOrder)) {
                jpaQuery = jpaQuery + " " + sortOrder;
            }
        }
        return entityManager().createQuery(jpaQuery, Merchant.class).getResultList();
    }
    
    public static Merchant Merchant.findMerchant(Long id) {
        if (id == null) return null;
        return entityManager().find(Merchant.class, id);
    }
    
    public static List<Merchant> Merchant.findMerchantEntries(int firstResult, int maxResults) {
        return entityManager().createQuery("SELECT o FROM Merchant o", Merchant.class).setFirstResult(firstResult).setMaxResults(maxResults).getResultList();
    }
    
    public static List<Merchant> Merchant.findMerchantEntries(int firstResult, int maxResults, String sortFieldName, String sortOrder) {
        String jpaQuery = "SELECT o FROM Merchant o";
        if (fieldNames4OrderClauseFilter.contains(sortFieldName)) {
            jpaQuery = jpaQuery + " ORDER BY " + sortFieldName;
            if ("ASC".equalsIgnoreCase(sortOrder) || "DESC".equalsIgnoreCase(sortOrder)) {
                jpaQuery = jpaQuery + " " + sortOrder;
            }
        }
        return entityManager().createQuery(jpaQuery, Merchant.class).setFirstResult(firstResult).setMaxResults(maxResults).getResultList();
    }
    
    @Transactional
    public void Merchant.persist() {
        if (this.entityManager == null) this.entityManager = entityManager();
        this.entityManager.persist(this);
    }
    
    @Transactional
    public void Merchant.remove() {
        if (this.entityManager == null) this.entityManager = entityManager();
        if (this.entityManager.contains(this)) {
            this.entityManager.remove(this);
        } else {
            Merchant attached = Merchant.findMerchant(this.id);
            this.entityManager.remove(attached);
        }
    }
    
    @Transactional
    public void Merchant.flush() {
        if (this.entityManager == null) this.entityManager = entityManager();
        this.entityManager.flush();
    }
    
    @Transactional
    public void Merchant.clear() {
        if (this.entityManager == null) this.entityManager = entityManager();
        this.entityManager.clear();
    }
    
    @Transactional
    public Merchant Merchant.merge() {
        if (this.entityManager == null) this.entityManager = entityManager();
        Merchant merged = this.entityManager.merge(this);
        this.entityManager.flush();
        return merged;
    }
    
}
