// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.azotov.roo.model;

import com.azotov.roo.model.Terminal;
import java.util.List;
import javax.persistence.EntityManager;
import javax.persistence.PersistenceContext;
import org.springframework.transaction.annotation.Transactional;

privileged aspect Terminal_Roo_Jpa_ActiveRecord {
    
    @PersistenceContext
    transient EntityManager Terminal.entityManager;
    
    public static final List<String> Terminal.fieldNames4OrderClauseFilter = java.util.Arrays.asList("TerminalNo", "Merchant");
    
    public static final EntityManager Terminal.entityManager() {
        EntityManager em = new Terminal().entityManager;
        if (em == null) throw new IllegalStateException("Entity manager has not been injected (is the Spring Aspects JAR configured as an AJC/AJDT aspects library?)");
        return em;
    }
    
    public static long Terminal.countTerminals() {
        return entityManager().createQuery("SELECT COUNT(o) FROM Terminal o", Long.class).getSingleResult();
    }
    
    public static List<Terminal> Terminal.findAllTerminals() {
        return entityManager().createQuery("SELECT o FROM Terminal o", Terminal.class).getResultList();
    }
    
    public static List<Terminal> Terminal.findAllTerminals(String sortFieldName, String sortOrder) {
        String jpaQuery = "SELECT o FROM Terminal o";
        if (fieldNames4OrderClauseFilter.contains(sortFieldName)) {
            jpaQuery = jpaQuery + " ORDER BY " + sortFieldName;
            if ("ASC".equalsIgnoreCase(sortOrder) || "DESC".equalsIgnoreCase(sortOrder)) {
                jpaQuery = jpaQuery + " " + sortOrder;
            }
        }
        return entityManager().createQuery(jpaQuery, Terminal.class).getResultList();
    }
    
    public static Terminal Terminal.findTerminal(Long id) {
        if (id == null) return null;
        return entityManager().find(Terminal.class, id);
    }
    
    public static List<Terminal> Terminal.findTerminalEntries(int firstResult, int maxResults) {
        return entityManager().createQuery("SELECT o FROM Terminal o", Terminal.class).setFirstResult(firstResult).setMaxResults(maxResults).getResultList();
    }
    
    public static List<Terminal> Terminal.findTerminalEntries(int firstResult, int maxResults, String sortFieldName, String sortOrder) {
        String jpaQuery = "SELECT o FROM Terminal o";
        if (fieldNames4OrderClauseFilter.contains(sortFieldName)) {
            jpaQuery = jpaQuery + " ORDER BY " + sortFieldName;
            if ("ASC".equalsIgnoreCase(sortOrder) || "DESC".equalsIgnoreCase(sortOrder)) {
                jpaQuery = jpaQuery + " " + sortOrder;
            }
        }
        return entityManager().createQuery(jpaQuery, Terminal.class).setFirstResult(firstResult).setMaxResults(maxResults).getResultList();
    }
    
    @Transactional
    public void Terminal.persist() {
        if (this.entityManager == null) this.entityManager = entityManager();
        this.entityManager.persist(this);
    }
    
    @Transactional
    public void Terminal.remove() {
        if (this.entityManager == null) this.entityManager = entityManager();
        if (this.entityManager.contains(this)) {
            this.entityManager.remove(this);
        } else {
            Terminal attached = Terminal.findTerminal(this.id);
            this.entityManager.remove(attached);
        }
    }
    
    @Transactional
    public void Terminal.flush() {
        if (this.entityManager == null) this.entityManager = entityManager();
        this.entityManager.flush();
    }
    
    @Transactional
    public void Terminal.clear() {
        if (this.entityManager == null) this.entityManager = entityManager();
        this.entityManager.clear();
    }
    
    @Transactional
    public Terminal Terminal.merge() {
        if (this.entityManager == null) this.entityManager = entityManager();
        Terminal merged = this.entityManager.merge(this);
        this.entityManager.flush();
        return merged;
    }
    
}
