// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.azotov.roo.model;

import com.azotov.roo.model.Terminal;
import flexjson.JSONDeserializer;
import flexjson.JSONSerializer;
import java.util.ArrayList;
import java.util.Collection;
import java.util.List;

privileged aspect Terminal_Roo_Json {
    
    public String Terminal.toJson() {
        return new JSONSerializer()
        .exclude("*.class").deepSerialize(this);
    }
    
    public String Terminal.toJson(String[] fields) {
        return new JSONSerializer()
        .include(fields).exclude("*.class").deepSerialize(this);
    }
    
    public static Terminal Terminal.fromJsonToTerminal(String json) {
        return new JSONDeserializer<Terminal>()
        .use(null, Terminal.class).deserialize(json);
    }
    
    public static String Terminal.toJsonArray(Collection<Terminal> collection) {
        return new JSONSerializer()
        .exclude("*.class").deepSerialize(collection);
    }
    
    public static String Terminal.toJsonArray(Collection<Terminal> collection, String[] fields) {
        return new JSONSerializer()
        .include(fields).exclude("*.class").deepSerialize(collection);
    }
    
    public static Collection<Terminal> Terminal.fromJsonArrayToTerminals(String json) {
        return new JSONDeserializer<List<Terminal>>()
        .use("values", Terminal.class).deserialize(json);
    }
    
}
