// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.azotov.roo.model;

import com.azotov.roo.model.Merchant;
import com.azotov.roo.model.Terminal;

privileged aspect Terminal_Roo_JavaBean {
    
    public Long Terminal.getTerminalNo() {
        return this.TerminalNo;
    }
    
    public void Terminal.setTerminalNo(Long TerminalNo) {
        this.TerminalNo = TerminalNo;
    }
    
    public Merchant Terminal.getMerchant() {
        return this.Merchant;
    }
    
    public void Terminal.setMerchant(Merchant Merchant) {
        this.Merchant = Merchant;
    }
    
}
