// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.azotov.roo.model;

import com.azotov.roo.model.Terminal;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Version;

privileged aspect Terminal_Roo_Jpa_Entity {
    
    declare @type: Terminal: @Entity;
    
    @Id
    @GeneratedValue(strategy = GenerationType.AUTO)
    @Column(name = "id")
    private Long Terminal.id;
    
    @Version
    @Column(name = "version")
    private Integer Terminal.version;
    
    public Long Terminal.getId() {
        return this.id;
    }
    
    public void Terminal.setId(Long id) {
        this.id = id;
    }
    
    public Integer Terminal.getVersion() {
        return this.version;
    }
    
    public void Terminal.setVersion(Integer version) {
        this.version = version;
    }
    
}
