// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.azotov.roo.model;

import com.azotov.roo.model.Branch;
import com.azotov.roo.model.BranchDataOnDemand;
import com.azotov.roo.model.BranchIntegrationTest;
import java.util.Iterator;
import java.util.List;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect BranchIntegrationTest_Roo_IntegrationTest {
    
    declare @type: BranchIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: BranchIntegrationTest: @ContextConfiguration(locations = "classpath*:/META-INF/spring/applicationContext*.xml");
    
    declare @type: BranchIntegrationTest: @Transactional;
    
    @Autowired
    BranchDataOnDemand BranchIntegrationTest.dod;
    
    @Test
    public void BranchIntegrationTest.testCountBranches() {
        Assert.assertNotNull("Data on demand for 'Branch' failed to initialize correctly", dod.getRandomBranch());
        long count = Branch.countBranches();
        Assert.assertTrue("Counter for 'Branch' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void BranchIntegrationTest.testFindBranch() {
        Branch obj = dod.getRandomBranch();
        Assert.assertNotNull("Data on demand for 'Branch' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Branch' failed to provide an identifier", id);
        obj = Branch.findBranch(id);
        Assert.assertNotNull("Find method for 'Branch' illegally returned null for id '" + id + "'", obj);
        Assert.assertEquals("Find method for 'Branch' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void BranchIntegrationTest.testFindAllBranches() {
        Assert.assertNotNull("Data on demand for 'Branch' failed to initialize correctly", dod.getRandomBranch());
        long count = Branch.countBranches();
        Assert.assertTrue("Too expensive to perform a find all test for 'Branch', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        List<Branch> result = Branch.findAllBranches();
        Assert.assertNotNull("Find all method for 'Branch' illegally returned null", result);
        Assert.assertTrue("Find all method for 'Branch' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void BranchIntegrationTest.testFindBranchEntries() {
        Assert.assertNotNull("Data on demand for 'Branch' failed to initialize correctly", dod.getRandomBranch());
        long count = Branch.countBranches();
        if (count > 20) count = 20;
        int firstResult = 0;
        int maxResults = (int) count;
        List<Branch> result = Branch.findBranchEntries(firstResult, maxResults);
        Assert.assertNotNull("Find entries method for 'Branch' illegally returned null", result);
        Assert.assertEquals("Find entries method for 'Branch' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void BranchIntegrationTest.testFlush() {
        Branch obj = dod.getRandomBranch();
        Assert.assertNotNull("Data on demand for 'Branch' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Branch' failed to provide an identifier", id);
        obj = Branch.findBranch(id);
        Assert.assertNotNull("Find method for 'Branch' illegally returned null for id '" + id + "'", obj);
        boolean modified =  dod.modifyBranch(obj);
        Integer currentVersion = obj.getVersion();
        obj.flush();
        Assert.assertTrue("Version for 'Branch' failed to increment on flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void BranchIntegrationTest.testMergeUpdate() {
        Branch obj = dod.getRandomBranch();
        Assert.assertNotNull("Data on demand for 'Branch' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Branch' failed to provide an identifier", id);
        obj = Branch.findBranch(id);
        boolean modified =  dod.modifyBranch(obj);
        Integer currentVersion = obj.getVersion();
        Branch merged = obj.merge();
        obj.flush();
        Assert.assertEquals("Identifier of merged object not the same as identifier of original object", merged.getId(), id);
        Assert.assertTrue("Version for 'Branch' failed to increment on merge and flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void BranchIntegrationTest.testPersist() {
        Assert.assertNotNull("Data on demand for 'Branch' failed to initialize correctly", dod.getRandomBranch());
        Branch obj = dod.getNewTransientBranch(Integer.MAX_VALUE);
        Assert.assertNotNull("Data on demand for 'Branch' failed to provide a new transient entity", obj);
        Assert.assertNull("Expected 'Branch' identifier to be null", obj.getId());
        try {
            obj.persist();
        } catch (final ConstraintViolationException e) {
            final StringBuilder msg = new StringBuilder();
            for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                final ConstraintViolation<?> cv = iter.next();
                msg.append("[").append(cv.getRootBean().getClass().getName()).append(".").append(cv.getPropertyPath()).append(": ").append(cv.getMessage()).append(" (invalid value = ").append(cv.getInvalidValue()).append(")").append("]");
            }
            throw new IllegalStateException(msg.toString(), e);
        }
        obj.flush();
        Assert.assertNotNull("Expected 'Branch' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void BranchIntegrationTest.testRemove() {
        Branch obj = dod.getRandomBranch();
        Assert.assertNotNull("Data on demand for 'Branch' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Branch' failed to provide an identifier", id);
        obj = Branch.findBranch(id);
        obj.remove();
        obj.flush();
        Assert.assertNull("Failed to remove 'Branch' with identifier '" + id + "'", Branch.findBranch(id));
    }
    
}
