// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.azotov.roo.model;

import com.azotov.roo.model.Branch;
import com.azotov.roo.model.BranchDataOnDemand;
import com.azotov.roo.model.MerchantDataOnDemand;
import java.security.SecureRandom;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.List;
import java.util.Random;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;

privileged aspect BranchDataOnDemand_Roo_DataOnDemand {
    
    declare @type: BranchDataOnDemand: @Component;
    
    private Random BranchDataOnDemand.rnd = new SecureRandom();
    
    private List<Branch> BranchDataOnDemand.data;
    
    @Autowired
    MerchantDataOnDemand BranchDataOnDemand.merchantDataOnDemand;
    
    public Branch BranchDataOnDemand.getNewTransientBranch(int index) {
        Branch obj = new Branch();
        setAddress(obj, index);
        setName(obj, index);
        return obj;
    }
    
    public void BranchDataOnDemand.setAddress(Branch obj, int index) {
        String Address = "Address_" + index;
        obj.setAddress(Address);
    }
    
    public void BranchDataOnDemand.setName(Branch obj, int index) {
        String Name = "Name_" + index;
        obj.setName(Name);
    }
    
    public Branch BranchDataOnDemand.getSpecificBranch(int index) {
        init();
        if (index < 0) {
            index = 0;
        }
        if (index > (data.size() - 1)) {
            index = data.size() - 1;
        }
        Branch obj = data.get(index);
        Long id = obj.getId();
        return Branch.findBranch(id);
    }
    
    public Branch BranchDataOnDemand.getRandomBranch() {
        init();
        Branch obj = data.get(rnd.nextInt(data.size()));
        Long id = obj.getId();
        return Branch.findBranch(id);
    }
    
    public boolean BranchDataOnDemand.modifyBranch(Branch obj) {
        return false;
    }
    
    public void BranchDataOnDemand.init() {
        int from = 0;
        int to = 10;
        data = Branch.findBranchEntries(from, to);
        if (data == null) {
            throw new IllegalStateException("Find entries implementation for 'Branch' illegally returned null");
        }
        if (!data.isEmpty()) {
            return;
        }
        
        data = new ArrayList<Branch>();
        for (int i = 0; i < 10; i++) {
            Branch obj = getNewTransientBranch(i);
            try {
                obj.persist();
            } catch (final ConstraintViolationException e) {
                final StringBuilder msg = new StringBuilder();
                for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                    final ConstraintViolation<?> cv = iter.next();
                    msg.append("[").append(cv.getRootBean().getClass().getName()).append(".").append(cv.getPropertyPath()).append(": ").append(cv.getMessage()).append(" (invalid value = ").append(cv.getInvalidValue()).append(")").append("]");
                }
                throw new IllegalStateException(msg.toString(), e);
            }
            obj.flush();
            data.add(obj);
        }
    }
    
}
