// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.azotov.roo.model;

import com.azotov.roo.model.Configuration;
import com.azotov.roo.model.ConfigurationDataOnDemand;
import java.security.SecureRandom;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.List;
import java.util.Random;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.springframework.stereotype.Component;

privileged aspect ConfigurationDataOnDemand_Roo_DataOnDemand {
    
    declare @type: ConfigurationDataOnDemand: @Component;
    
    private Random ConfigurationDataOnDemand.rnd = new SecureRandom();
    
    private List<Configuration> ConfigurationDataOnDemand.data;
    
    public Configuration ConfigurationDataOnDemand.getNewTransientConfiguration(int index) {
        Configuration obj = new Configuration();
        setName(obj, index);
        setRate(obj, index);
        return obj;
    }
    
    public void ConfigurationDataOnDemand.setName(Configuration obj, int index) {
        String name = "name_" + index;
        if (name.length() > 40) {
            name = name.substring(0, 40);
        }
        obj.setName(name);
    }
    
    public void ConfigurationDataOnDemand.setRate(Configuration obj, int index) {
        Double Rate = new Integer(index).doubleValue();
        obj.setRate(Rate);
    }
    
    public Configuration ConfigurationDataOnDemand.getSpecificConfiguration(int index) {
        init();
        if (index < 0) {
            index = 0;
        }
        if (index > (data.size() - 1)) {
            index = data.size() - 1;
        }
        Configuration obj = data.get(index);
        Long id = obj.getId();
        return Configuration.findConfiguration(id);
    }
    
    public Configuration ConfigurationDataOnDemand.getRandomConfiguration() {
        init();
        Configuration obj = data.get(rnd.nextInt(data.size()));
        Long id = obj.getId();
        return Configuration.findConfiguration(id);
    }
    
    public boolean ConfigurationDataOnDemand.modifyConfiguration(Configuration obj) {
        return false;
    }
    
    public void ConfigurationDataOnDemand.init() {
        int from = 0;
        int to = 10;
        data = Configuration.findConfigurationEntries(from, to);
        if (data == null) {
            throw new IllegalStateException("Find entries implementation for 'Configuration' illegally returned null");
        }
        if (!data.isEmpty()) {
            return;
        }
        
        data = new ArrayList<Configuration>();
        for (int i = 0; i < 10; i++) {
            Configuration obj = getNewTransientConfiguration(i);
            try {
                obj.persist();
            } catch (final ConstraintViolationException e) {
                final StringBuilder msg = new StringBuilder();
                for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                    final ConstraintViolation<?> cv = iter.next();
                    msg.append("[").append(cv.getRootBean().getClass().getName()).append(".").append(cv.getPropertyPath()).append(": ").append(cv.getMessage()).append(" (invalid value = ").append(cv.getInvalidValue()).append(")").append("]");
                }
                throw new IllegalStateException(msg.toString(), e);
            }
            obj.flush();
            data.add(obj);
        }
    }
    
}
