// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.azotov.roo.model;

import com.azotov.roo.model.IssuerAgent;
import com.azotov.roo.model.IssuerAgentDataOnDemand;
import java.security.SecureRandom;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.List;
import java.util.Random;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.springframework.stereotype.Component;

privileged aspect IssuerAgentDataOnDemand_Roo_DataOnDemand {
    
    declare @type: IssuerAgentDataOnDemand: @Component;
    
    private Random IssuerAgentDataOnDemand.rnd = new SecureRandom();
    
    private List<IssuerAgent> IssuerAgentDataOnDemand.data;
    
    public IssuerAgent IssuerAgentDataOnDemand.getNewTransientIssuerAgent(int index) {
        IssuerAgent obj = new IssuerAgent();
        setName(obj, index);
        return obj;
    }
    
    public void IssuerAgentDataOnDemand.setName(IssuerAgent obj, int index) {
        String Name = "Name_" + index;
        obj.setName(Name);
    }
    
    public IssuerAgent IssuerAgentDataOnDemand.getSpecificIssuerAgent(int index) {
        init();
        if (index < 0) {
            index = 0;
        }
        if (index > (data.size() - 1)) {
            index = data.size() - 1;
        }
        IssuerAgent obj = data.get(index);
        Long id = obj.getId();
        return IssuerAgent.findIssuerAgent(id);
    }
    
    public IssuerAgent IssuerAgentDataOnDemand.getRandomIssuerAgent() {
        init();
        IssuerAgent obj = data.get(rnd.nextInt(data.size()));
        Long id = obj.getId();
        return IssuerAgent.findIssuerAgent(id);
    }
    
    public boolean IssuerAgentDataOnDemand.modifyIssuerAgent(IssuerAgent obj) {
        return false;
    }
    
    public void IssuerAgentDataOnDemand.init() {
        int from = 0;
        int to = 10;
        data = IssuerAgent.findIssuerAgentEntries(from, to);
        if (data == null) {
            throw new IllegalStateException("Find entries implementation for 'IssuerAgent' illegally returned null");
        }
        if (!data.isEmpty()) {
            return;
        }
        
        data = new ArrayList<IssuerAgent>();
        for (int i = 0; i < 10; i++) {
            IssuerAgent obj = getNewTransientIssuerAgent(i);
            try {
                obj.persist();
            } catch (final ConstraintViolationException e) {
                final StringBuilder msg = new StringBuilder();
                for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                    final ConstraintViolation<?> cv = iter.next();
                    msg.append("[").append(cv.getRootBean().getClass().getName()).append(".").append(cv.getPropertyPath()).append(": ").append(cv.getMessage()).append(" (invalid value = ").append(cv.getInvalidValue()).append(")").append("]");
                }
                throw new IllegalStateException(msg.toString(), e);
            }
            obj.flush();
            data.add(obj);
        }
    }
    
}
