// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.azotov.roo.model;

import com.azotov.roo.model.IssuerIntegrationTest;
import org.springframework.beans.factory.annotation.Configurable;

privileged aspect IssuerIntegrationTest_Roo_Configurable {
    
    declare @type: IssuerIntegrationTest: @Configurable;
    
}
