// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.azotov.roo.model;

import com.azotov.roo.model.IssuerAgent;
import com.azotov.roo.model.IssuerAgentDataOnDemand;
import com.azotov.roo.model.IssuerAgentIntegrationTest;
import java.util.Iterator;
import java.util.List;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect IssuerAgentIntegrationTest_Roo_IntegrationTest {
    
    declare @type: IssuerAgentIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: IssuerAgentIntegrationTest: @ContextConfiguration(locations = "classpath*:/META-INF/spring/applicationContext*.xml");
    
    declare @type: IssuerAgentIntegrationTest: @Transactional;
    
    @Autowired
    IssuerAgentDataOnDemand IssuerAgentIntegrationTest.dod;
    
    @Test
    public void IssuerAgentIntegrationTest.testCountIssuerAgents() {
        Assert.assertNotNull("Data on demand for 'IssuerAgent' failed to initialize correctly", dod.getRandomIssuerAgent());
        long count = IssuerAgent.countIssuerAgents();
        Assert.assertTrue("Counter for 'IssuerAgent' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void IssuerAgentIntegrationTest.testFindIssuerAgent() {
        IssuerAgent obj = dod.getRandomIssuerAgent();
        Assert.assertNotNull("Data on demand for 'IssuerAgent' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'IssuerAgent' failed to provide an identifier", id);
        obj = IssuerAgent.findIssuerAgent(id);
        Assert.assertNotNull("Find method for 'IssuerAgent' illegally returned null for id '" + id + "'", obj);
        Assert.assertEquals("Find method for 'IssuerAgent' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void IssuerAgentIntegrationTest.testFindAllIssuerAgents() {
        Assert.assertNotNull("Data on demand for 'IssuerAgent' failed to initialize correctly", dod.getRandomIssuerAgent());
        long count = IssuerAgent.countIssuerAgents();
        Assert.assertTrue("Too expensive to perform a find all test for 'IssuerAgent', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        List<IssuerAgent> result = IssuerAgent.findAllIssuerAgents();
        Assert.assertNotNull("Find all method for 'IssuerAgent' illegally returned null", result);
        Assert.assertTrue("Find all method for 'IssuerAgent' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void IssuerAgentIntegrationTest.testFindIssuerAgentEntries() {
        Assert.assertNotNull("Data on demand for 'IssuerAgent' failed to initialize correctly", dod.getRandomIssuerAgent());
        long count = IssuerAgent.countIssuerAgents();
        if (count > 20) count = 20;
        int firstResult = 0;
        int maxResults = (int) count;
        List<IssuerAgent> result = IssuerAgent.findIssuerAgentEntries(firstResult, maxResults);
        Assert.assertNotNull("Find entries method for 'IssuerAgent' illegally returned null", result);
        Assert.assertEquals("Find entries method for 'IssuerAgent' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void IssuerAgentIntegrationTest.testFlush() {
        IssuerAgent obj = dod.getRandomIssuerAgent();
        Assert.assertNotNull("Data on demand for 'IssuerAgent' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'IssuerAgent' failed to provide an identifier", id);
        obj = IssuerAgent.findIssuerAgent(id);
        Assert.assertNotNull("Find method for 'IssuerAgent' illegally returned null for id '" + id + "'", obj);
        boolean modified =  dod.modifyIssuerAgent(obj);
        Integer currentVersion = obj.getVersion();
        obj.flush();
        Assert.assertTrue("Version for 'IssuerAgent' failed to increment on flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void IssuerAgentIntegrationTest.testMergeUpdate() {
        IssuerAgent obj = dod.getRandomIssuerAgent();
        Assert.assertNotNull("Data on demand for 'IssuerAgent' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'IssuerAgent' failed to provide an identifier", id);
        obj = IssuerAgent.findIssuerAgent(id);
        boolean modified =  dod.modifyIssuerAgent(obj);
        Integer currentVersion = obj.getVersion();
        IssuerAgent merged = obj.merge();
        obj.flush();
        Assert.assertEquals("Identifier of merged object not the same as identifier of original object", merged.getId(), id);
        Assert.assertTrue("Version for 'IssuerAgent' failed to increment on merge and flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void IssuerAgentIntegrationTest.testPersist() {
        Assert.assertNotNull("Data on demand for 'IssuerAgent' failed to initialize correctly", dod.getRandomIssuerAgent());
        IssuerAgent obj = dod.getNewTransientIssuerAgent(Integer.MAX_VALUE);
        Assert.assertNotNull("Data on demand for 'IssuerAgent' failed to provide a new transient entity", obj);
        Assert.assertNull("Expected 'IssuerAgent' identifier to be null", obj.getId());
        try {
            obj.persist();
        } catch (final ConstraintViolationException e) {
            final StringBuilder msg = new StringBuilder();
            for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                final ConstraintViolation<?> cv = iter.next();
                msg.append("[").append(cv.getRootBean().getClass().getName()).append(".").append(cv.getPropertyPath()).append(": ").append(cv.getMessage()).append(" (invalid value = ").append(cv.getInvalidValue()).append(")").append("]");
            }
            throw new IllegalStateException(msg.toString(), e);
        }
        obj.flush();
        Assert.assertNotNull("Expected 'IssuerAgent' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void IssuerAgentIntegrationTest.testRemove() {
        IssuerAgent obj = dod.getRandomIssuerAgent();
        Assert.assertNotNull("Data on demand for 'IssuerAgent' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'IssuerAgent' failed to provide an identifier", id);
        obj = IssuerAgent.findIssuerAgent(id);
        obj.remove();
        obj.flush();
        Assert.assertNull("Failed to remove 'IssuerAgent' with identifier '" + id + "'", IssuerAgent.findIssuerAgent(id));
    }
    
}
