// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.azotov.roo.model;

import com.azotov.roo.model.Terminal;
import com.azotov.roo.model.TerminalDataOnDemand;
import com.azotov.roo.model.TerminalIntegrationTest;
import java.util.Iterator;
import java.util.List;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect TerminalIntegrationTest_Roo_IntegrationTest {
    
    declare @type: TerminalIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: TerminalIntegrationTest: @ContextConfiguration(locations = "classpath*:/META-INF/spring/applicationContext*.xml");
    
    declare @type: TerminalIntegrationTest: @Transactional;
    
    @Autowired
    TerminalDataOnDemand TerminalIntegrationTest.dod;
    
    @Test
    public void TerminalIntegrationTest.testCountTerminals() {
        Assert.assertNotNull("Data on demand for 'Terminal' failed to initialize correctly", dod.getRandomTerminal());
        long count = Terminal.countTerminals();
        Assert.assertTrue("Counter for 'Terminal' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void TerminalIntegrationTest.testFindTerminal() {
        Terminal obj = dod.getRandomTerminal();
        Assert.assertNotNull("Data on demand for 'Terminal' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Terminal' failed to provide an identifier", id);
        obj = Terminal.findTerminal(id);
        Assert.assertNotNull("Find method for 'Terminal' illegally returned null for id '" + id + "'", obj);
        Assert.assertEquals("Find method for 'Terminal' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void TerminalIntegrationTest.testFindAllTerminals() {
        Assert.assertNotNull("Data on demand for 'Terminal' failed to initialize correctly", dod.getRandomTerminal());
        long count = Terminal.countTerminals();
        Assert.assertTrue("Too expensive to perform a find all test for 'Terminal', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        List<Terminal> result = Terminal.findAllTerminals();
        Assert.assertNotNull("Find all method for 'Terminal' illegally returned null", result);
        Assert.assertTrue("Find all method for 'Terminal' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void TerminalIntegrationTest.testFindTerminalEntries() {
        Assert.assertNotNull("Data on demand for 'Terminal' failed to initialize correctly", dod.getRandomTerminal());
        long count = Terminal.countTerminals();
        if (count > 20) count = 20;
        int firstResult = 0;
        int maxResults = (int) count;
        List<Terminal> result = Terminal.findTerminalEntries(firstResult, maxResults);
        Assert.assertNotNull("Find entries method for 'Terminal' illegally returned null", result);
        Assert.assertEquals("Find entries method for 'Terminal' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void TerminalIntegrationTest.testFlush() {
        Terminal obj = dod.getRandomTerminal();
        Assert.assertNotNull("Data on demand for 'Terminal' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Terminal' failed to provide an identifier", id);
        obj = Terminal.findTerminal(id);
        Assert.assertNotNull("Find method for 'Terminal' illegally returned null for id '" + id + "'", obj);
        boolean modified =  dod.modifyTerminal(obj);
        Integer currentVersion = obj.getVersion();
        obj.flush();
        Assert.assertTrue("Version for 'Terminal' failed to increment on flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void TerminalIntegrationTest.testMergeUpdate() {
        Terminal obj = dod.getRandomTerminal();
        Assert.assertNotNull("Data on demand for 'Terminal' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Terminal' failed to provide an identifier", id);
        obj = Terminal.findTerminal(id);
        boolean modified =  dod.modifyTerminal(obj);
        Integer currentVersion = obj.getVersion();
        Terminal merged = obj.merge();
        obj.flush();
        Assert.assertEquals("Identifier of merged object not the same as identifier of original object", merged.getId(), id);
        Assert.assertTrue("Version for 'Terminal' failed to increment on merge and flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void TerminalIntegrationTest.testPersist() {
        Assert.assertNotNull("Data on demand for 'Terminal' failed to initialize correctly", dod.getRandomTerminal());
        Terminal obj = dod.getNewTransientTerminal(Integer.MAX_VALUE);
        Assert.assertNotNull("Data on demand for 'Terminal' failed to provide a new transient entity", obj);
        Assert.assertNull("Expected 'Terminal' identifier to be null", obj.getId());
        try {
            obj.persist();
        } catch (final ConstraintViolationException e) {
            final StringBuilder msg = new StringBuilder();
            for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                final ConstraintViolation<?> cv = iter.next();
                msg.append("[").append(cv.getRootBean().getClass().getName()).append(".").append(cv.getPropertyPath()).append(": ").append(cv.getMessage()).append(" (invalid value = ").append(cv.getInvalidValue()).append(")").append("]");
            }
            throw new IllegalStateException(msg.toString(), e);
        }
        obj.flush();
        Assert.assertNotNull("Expected 'Terminal' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void TerminalIntegrationTest.testRemove() {
        Terminal obj = dod.getRandomTerminal();
        Assert.assertNotNull("Data on demand for 'Terminal' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Terminal' failed to provide an identifier", id);
        obj = Terminal.findTerminal(id);
        obj.remove();
        obj.flush();
        Assert.assertNull("Failed to remove 'Terminal' with identifier '" + id + "'", Terminal.findTerminal(id));
    }
    
}
