// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.azotov.roo.model;

import com.azotov.roo.model.MerchantDataOnDemand;
import com.azotov.roo.model.Terminal;
import com.azotov.roo.model.TerminalDataOnDemand;
import java.security.SecureRandom;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.List;
import java.util.Random;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;

privileged aspect TerminalDataOnDemand_Roo_DataOnDemand {
    
    declare @type: TerminalDataOnDemand: @Component;
    
    private Random TerminalDataOnDemand.rnd = new SecureRandom();
    
    private List<Terminal> TerminalDataOnDemand.data;
    
    @Autowired
    MerchantDataOnDemand TerminalDataOnDemand.merchantDataOnDemand;
    
    public Terminal TerminalDataOnDemand.getNewTransientTerminal(int index) {
        Terminal obj = new Terminal();
        setTerminalNo(obj, index);
        return obj;
    }
    
    public void TerminalDataOnDemand.setTerminalNo(Terminal obj, int index) {
        Long TerminalNo = new Integer(index).longValue();
        obj.setTerminalNo(TerminalNo);
    }
    
    public Terminal TerminalDataOnDemand.getSpecificTerminal(int index) {
        init();
        if (index < 0) {
            index = 0;
        }
        if (index > (data.size() - 1)) {
            index = data.size() - 1;
        }
        Terminal obj = data.get(index);
        Long id = obj.getId();
        return Terminal.findTerminal(id);
    }
    
    public Terminal TerminalDataOnDemand.getRandomTerminal() {
        init();
        Terminal obj = data.get(rnd.nextInt(data.size()));
        Long id = obj.getId();
        return Terminal.findTerminal(id);
    }
    
    public boolean TerminalDataOnDemand.modifyTerminal(Terminal obj) {
        return false;
    }
    
    public void TerminalDataOnDemand.init() {
        int from = 0;
        int to = 10;
        data = Terminal.findTerminalEntries(from, to);
        if (data == null) {
            throw new IllegalStateException("Find entries implementation for 'Terminal' illegally returned null");
        }
        if (!data.isEmpty()) {
            return;
        }
        
        data = new ArrayList<Terminal>();
        for (int i = 0; i < 10; i++) {
            Terminal obj = getNewTransientTerminal(i);
            try {
                obj.persist();
            } catch (final ConstraintViolationException e) {
                final StringBuilder msg = new StringBuilder();
                for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                    final ConstraintViolation<?> cv = iter.next();
                    msg.append("[").append(cv.getRootBean().getClass().getName()).append(".").append(cv.getPropertyPath()).append(": ").append(cv.getMessage()).append(" (invalid value = ").append(cv.getInvalidValue()).append(")").append("]");
                }
                throw new IllegalStateException(msg.toString(), e);
            }
            obj.flush();
            data.add(obj);
        }
    }
    
}
