// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.azotov.roo.web;

import com.azotov.roo.model.Branch;
import com.azotov.roo.model.Configuration;
import com.azotov.roo.model.Issuer;
import com.azotov.roo.model.IssuerAgent;
import com.azotov.roo.model.Merchant;
import com.azotov.roo.model.Terminal;
import com.azotov.roo.web.ApplicationConversionServiceFactoryBean;
import org.springframework.beans.factory.annotation.Configurable;
import org.springframework.core.convert.converter.Converter;
import org.springframework.format.FormatterRegistry;

privileged aspect ApplicationConversionServiceFactoryBean_Roo_ConversionService {
    
    declare @type: ApplicationConversionServiceFactoryBean: @Configurable;
    
    public Converter<Branch, String> ApplicationConversionServiceFactoryBean.getBranchToStringConverter() {
        return new org.springframework.core.convert.converter.Converter<com.azotov.roo.model.Branch, java.lang.String>() {
            public String convert(Branch branch) {
                return new StringBuilder().append(branch.getAddress()).append(' ').append(branch.getName()).toString();
            }
        };
    }
    
    public Converter<Long, Branch> ApplicationConversionServiceFactoryBean.getIdToBranchConverter() {
        return new org.springframework.core.convert.converter.Converter<java.lang.Long, com.azotov.roo.model.Branch>() {
            public com.azotov.roo.model.Branch convert(java.lang.Long id) {
                return Branch.findBranch(id);
            }
        };
    }
    
    public Converter<String, Branch> ApplicationConversionServiceFactoryBean.getStringToBranchConverter() {
        return new org.springframework.core.convert.converter.Converter<java.lang.String, com.azotov.roo.model.Branch>() {
            public com.azotov.roo.model.Branch convert(String id) {
                return getObject().convert(getObject().convert(id, Long.class), Branch.class);
            }
        };
    }
    
    public Converter<Configuration, String> ApplicationConversionServiceFactoryBean.getConfigurationToStringConverter() {
        return new org.springframework.core.convert.converter.Converter<com.azotov.roo.model.Configuration, java.lang.String>() {
            public String convert(Configuration configuration) {
                return new StringBuilder().append(configuration.getName()).append(' ').append(configuration.getRate()).toString();
            }
        };
    }
    
    public Converter<Long, Configuration> ApplicationConversionServiceFactoryBean.getIdToConfigurationConverter() {
        return new org.springframework.core.convert.converter.Converter<java.lang.Long, com.azotov.roo.model.Configuration>() {
            public com.azotov.roo.model.Configuration convert(java.lang.Long id) {
                return Configuration.findConfiguration(id);
            }
        };
    }
    
    public Converter<String, Configuration> ApplicationConversionServiceFactoryBean.getStringToConfigurationConverter() {
        return new org.springframework.core.convert.converter.Converter<java.lang.String, com.azotov.roo.model.Configuration>() {
            public com.azotov.roo.model.Configuration convert(String id) {
                return getObject().convert(getObject().convert(id, Long.class), Configuration.class);
            }
        };
    }
    
    public Converter<Issuer, String> ApplicationConversionServiceFactoryBean.getIssuerToStringConverter() {
        return new org.springframework.core.convert.converter.Converter<com.azotov.roo.model.Issuer, java.lang.String>() {
            public String convert(Issuer issuer) {
                return new StringBuilder().append(issuer.getName()).append(' ').append(issuer.getRate()).toString();
            }
        };
    }
    
    public Converter<Long, Issuer> ApplicationConversionServiceFactoryBean.getIdToIssuerConverter() {
        return new org.springframework.core.convert.converter.Converter<java.lang.Long, com.azotov.roo.model.Issuer>() {
            public com.azotov.roo.model.Issuer convert(java.lang.Long id) {
                return Issuer.findIssuer(id);
            }
        };
    }
    
    public Converter<String, Issuer> ApplicationConversionServiceFactoryBean.getStringToIssuerConverter() {
        return new org.springframework.core.convert.converter.Converter<java.lang.String, com.azotov.roo.model.Issuer>() {
            public com.azotov.roo.model.Issuer convert(String id) {
                return getObject().convert(getObject().convert(id, Long.class), Issuer.class);
            }
        };
    }
    
    public Converter<IssuerAgent, String> ApplicationConversionServiceFactoryBean.getIssuerAgentToStringConverter() {
        return new org.springframework.core.convert.converter.Converter<com.azotov.roo.model.IssuerAgent, java.lang.String>() {
            public String convert(IssuerAgent issuerAgent) {
                return new StringBuilder().append(issuerAgent.getName()).toString();
            }
        };
    }
    
    public Converter<Long, IssuerAgent> ApplicationConversionServiceFactoryBean.getIdToIssuerAgentConverter() {
        return new org.springframework.core.convert.converter.Converter<java.lang.Long, com.azotov.roo.model.IssuerAgent>() {
            public com.azotov.roo.model.IssuerAgent convert(java.lang.Long id) {
                return IssuerAgent.findIssuerAgent(id);
            }
        };
    }
    
    public Converter<String, IssuerAgent> ApplicationConversionServiceFactoryBean.getStringToIssuerAgentConverter() {
        return new org.springframework.core.convert.converter.Converter<java.lang.String, com.azotov.roo.model.IssuerAgent>() {
            public com.azotov.roo.model.IssuerAgent convert(String id) {
                return getObject().convert(getObject().convert(id, Long.class), IssuerAgent.class);
            }
        };
    }
    
    public Converter<Merchant, String> ApplicationConversionServiceFactoryBean.getMerchantToStringConverter() {
        return new org.springframework.core.convert.converter.Converter<com.azotov.roo.model.Merchant, java.lang.String>() {
            public String convert(Merchant merchant) {
                return new StringBuilder().append(merchant.getName()).append(' ').append(merchant.getCompanyName()).append(' ').append(merchant.getCompanyRegisterNumber()).append(' ').append(merchant.getBusinessNature()).toString();
            }
        };
    }
    
    public Converter<Long, Merchant> ApplicationConversionServiceFactoryBean.getIdToMerchantConverter() {
        return new org.springframework.core.convert.converter.Converter<java.lang.Long, com.azotov.roo.model.Merchant>() {
            public com.azotov.roo.model.Merchant convert(java.lang.Long id) {
                return Merchant.findMerchant(id);
            }
        };
    }
    
    public Converter<String, Merchant> ApplicationConversionServiceFactoryBean.getStringToMerchantConverter() {
        return new org.springframework.core.convert.converter.Converter<java.lang.String, com.azotov.roo.model.Merchant>() {
            public com.azotov.roo.model.Merchant convert(String id) {
                return getObject().convert(getObject().convert(id, Long.class), Merchant.class);
            }
        };
    }
    
    public Converter<Terminal, String> ApplicationConversionServiceFactoryBean.getTerminalToStringConverter() {
        return new org.springframework.core.convert.converter.Converter<com.azotov.roo.model.Terminal, java.lang.String>() {
            public String convert(Terminal terminal) {
                return new StringBuilder().append(terminal.getTerminalNo()).toString();
            }
        };
    }
    
    public Converter<Long, Terminal> ApplicationConversionServiceFactoryBean.getIdToTerminalConverter() {
        return new org.springframework.core.convert.converter.Converter<java.lang.Long, com.azotov.roo.model.Terminal>() {
            public com.azotov.roo.model.Terminal convert(java.lang.Long id) {
                return Terminal.findTerminal(id);
            }
        };
    }
    
    public Converter<String, Terminal> ApplicationConversionServiceFactoryBean.getStringToTerminalConverter() {
        return new org.springframework.core.convert.converter.Converter<java.lang.String, com.azotov.roo.model.Terminal>() {
            public com.azotov.roo.model.Terminal convert(String id) {
                return getObject().convert(getObject().convert(id, Long.class), Terminal.class);
            }
        };
    }
    
    public void ApplicationConversionServiceFactoryBean.installLabelConverters(FormatterRegistry registry) {
        registry.addConverter(getBranchToStringConverter());
        registry.addConverter(getIdToBranchConverter());
        registry.addConverter(getStringToBranchConverter());
        registry.addConverter(getConfigurationToStringConverter());
        registry.addConverter(getIdToConfigurationConverter());
        registry.addConverter(getStringToConfigurationConverter());
        registry.addConverter(getIssuerToStringConverter());
        registry.addConverter(getIdToIssuerConverter());
        registry.addConverter(getStringToIssuerConverter());
        registry.addConverter(getIssuerAgentToStringConverter());
        registry.addConverter(getIdToIssuerAgentConverter());
        registry.addConverter(getStringToIssuerAgentConverter());
        registry.addConverter(getMerchantToStringConverter());
        registry.addConverter(getIdToMerchantConverter());
        registry.addConverter(getStringToMerchantConverter());
        registry.addConverter(getTerminalToStringConverter());
        registry.addConverter(getIdToTerminalConverter());
        registry.addConverter(getStringToTerminalConverter());
    }
    
    public void ApplicationConversionServiceFactoryBean.afterPropertiesSet() {
        super.afterPropertiesSet();
        installLabelConverters(getObject());
    }
    
}
