// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.azotov.roo.web;

import com.azotov.roo.model.Branch;
import com.azotov.roo.model.Merchant;
import com.azotov.roo.web.BranchController;
import java.io.UnsupportedEncodingException;
import javax.servlet.http.HttpServletRequest;
import javax.validation.Valid;
import org.springframework.ui.Model;
import org.springframework.validation.BindingResult;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.util.UriUtils;
import org.springframework.web.util.WebUtils;

privileged aspect BranchController_Roo_Controller {
    
    @RequestMapping(method = RequestMethod.POST, produces = "text/html")
    public String BranchController.create(@Valid Branch branch, BindingResult bindingResult, Model uiModel, HttpServletRequest httpServletRequest) {
        if (bindingResult.hasErrors()) {
            populateEditForm(uiModel, branch);
            return "branches/create";
        }
        uiModel.asMap().clear();
        branch.persist();
        return "redirect:/branches/" + encodeUrlPathSegment(branch.getId().toString(), httpServletRequest);
    }
    
    @RequestMapping(params = "form", produces = "text/html")
    public String BranchController.createForm(Model uiModel) {
        populateEditForm(uiModel, new Branch());
        return "branches/create";
    }
    
    @RequestMapping(value = "/{id}", produces = "text/html")
    public String BranchController.show(@PathVariable("id") Long id, Model uiModel) {
        uiModel.addAttribute("branch", Branch.findBranch(id));
        uiModel.addAttribute("itemId", id);
        return "branches/show";
    }
    
    @RequestMapping(produces = "text/html")
    public String BranchController.list(@RequestParam(value = "page", required = false) Integer page, @RequestParam(value = "size", required = false) Integer size, @RequestParam(value = "sortFieldName", required = false) String sortFieldName, @RequestParam(value = "sortOrder", required = false) String sortOrder, Model uiModel) {
        if (page != null || size != null) {
            int sizeNo = size == null ? 10 : size.intValue();
            final int firstResult = page == null ? 0 : (page.intValue() - 1) * sizeNo;
            uiModel.addAttribute("branches", Branch.findBranchEntries(firstResult, sizeNo, sortFieldName, sortOrder));
            float nrOfPages = (float) Branch.countBranches() / sizeNo;
            uiModel.addAttribute("maxPages", (int) ((nrOfPages > (int) nrOfPages || nrOfPages == 0.0) ? nrOfPages + 1 : nrOfPages));
        } else {
            uiModel.addAttribute("branches", Branch.findAllBranches(sortFieldName, sortOrder));
        }
        return "branches/list";
    }
    
    @RequestMapping(method = RequestMethod.PUT, produces = "text/html")
    public String BranchController.update(@Valid Branch branch, BindingResult bindingResult, Model uiModel, HttpServletRequest httpServletRequest) {
        if (bindingResult.hasErrors()) {
            populateEditForm(uiModel, branch);
            return "branches/update";
        }
        uiModel.asMap().clear();
        branch.merge();
        return "redirect:/branches/" + encodeUrlPathSegment(branch.getId().toString(), httpServletRequest);
    }
    
    @RequestMapping(value = "/{id}", params = "form", produces = "text/html")
    public String BranchController.updateForm(@PathVariable("id") Long id, Model uiModel) {
        populateEditForm(uiModel, Branch.findBranch(id));
        return "branches/update";
    }
    
    @RequestMapping(value = "/{id}", method = RequestMethod.DELETE, produces = "text/html")
    public String BranchController.delete(@PathVariable("id") Long id, @RequestParam(value = "page", required = false) Integer page, @RequestParam(value = "size", required = false) Integer size, Model uiModel) {
        Branch branch = Branch.findBranch(id);
        branch.remove();
        uiModel.asMap().clear();
        uiModel.addAttribute("page", (page == null) ? "1" : page.toString());
        uiModel.addAttribute("size", (size == null) ? "10" : size.toString());
        return "redirect:/branches";
    }
    
    void BranchController.populateEditForm(Model uiModel, Branch branch) {
        uiModel.addAttribute("branch", branch);
        uiModel.addAttribute("merchants", Merchant.findAllMerchants());
    }
    
    String BranchController.encodeUrlPathSegment(String pathSegment, HttpServletRequest httpServletRequest) {
        String enc = httpServletRequest.getCharacterEncoding();
        if (enc == null) {
            enc = WebUtils.DEFAULT_CHARACTER_ENCODING;
        }
        try {
            pathSegment = UriUtils.encodePathSegment(pathSegment, enc);
        } catch (UnsupportedEncodingException uee) {}
        return pathSegment;
    }
    
}
