// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.azotov.roo.web;

import com.azotov.roo.model.Issuer;
import com.azotov.roo.web.IssuerController;
import java.io.UnsupportedEncodingException;
import javax.servlet.http.HttpServletRequest;
import javax.validation.Valid;
import org.springframework.ui.Model;
import org.springframework.validation.BindingResult;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.util.UriUtils;
import org.springframework.web.util.WebUtils;

privileged aspect IssuerController_Roo_Controller {
    
    @RequestMapping(method = RequestMethod.POST, produces = "text/html")
    public String IssuerController.create(@Valid Issuer issuer, BindingResult bindingResult, Model uiModel, HttpServletRequest httpServletRequest) {
        if (bindingResult.hasErrors()) {
            populateEditForm(uiModel, issuer);
            return "issuers/create";
        }
        uiModel.asMap().clear();
        issuer.persist();
        return "redirect:/issuers/" + encodeUrlPathSegment(issuer.getId().toString(), httpServletRequest);
    }
    
    @RequestMapping(params = "form", produces = "text/html")
    public String IssuerController.createForm(Model uiModel) {
        populateEditForm(uiModel, new Issuer());
        return "issuers/create";
    }
    
    @RequestMapping(value = "/{id}", produces = "text/html")
    public String IssuerController.show(@PathVariable("id") Long id, Model uiModel) {
        uiModel.addAttribute("issuer", Issuer.findIssuer(id));
        uiModel.addAttribute("itemId", id);
        return "issuers/show";
    }
    
    @RequestMapping(produces = "text/html")
    public String IssuerController.list(@RequestParam(value = "page", required = false) Integer page, @RequestParam(value = "size", required = false) Integer size, @RequestParam(value = "sortFieldName", required = false) String sortFieldName, @RequestParam(value = "sortOrder", required = false) String sortOrder, Model uiModel) {
        if (page != null || size != null) {
            int sizeNo = size == null ? 10 : size.intValue();
            final int firstResult = page == null ? 0 : (page.intValue() - 1) * sizeNo;
            uiModel.addAttribute("issuers", Issuer.findIssuerEntries(firstResult, sizeNo, sortFieldName, sortOrder));
            float nrOfPages = (float) Issuer.countIssuers() / sizeNo;
            uiModel.addAttribute("maxPages", (int) ((nrOfPages > (int) nrOfPages || nrOfPages == 0.0) ? nrOfPages + 1 : nrOfPages));
        } else {
            uiModel.addAttribute("issuers", Issuer.findAllIssuers(sortFieldName, sortOrder));
        }
        return "issuers/list";
    }
    
    @RequestMapping(method = RequestMethod.PUT, produces = "text/html")
    public String IssuerController.update(@Valid Issuer issuer, BindingResult bindingResult, Model uiModel, HttpServletRequest httpServletRequest) {
        if (bindingResult.hasErrors()) {
            populateEditForm(uiModel, issuer);
            return "issuers/update";
        }
        uiModel.asMap().clear();
        issuer.merge();
        return "redirect:/issuers/" + encodeUrlPathSegment(issuer.getId().toString(), httpServletRequest);
    }
    
    @RequestMapping(value = "/{id}", params = "form", produces = "text/html")
    public String IssuerController.updateForm(@PathVariable("id") Long id, Model uiModel) {
        populateEditForm(uiModel, Issuer.findIssuer(id));
        return "issuers/update";
    }
    
    @RequestMapping(value = "/{id}", method = RequestMethod.DELETE, produces = "text/html")
    public String IssuerController.delete(@PathVariable("id") Long id, @RequestParam(value = "page", required = false) Integer page, @RequestParam(value = "size", required = false) Integer size, Model uiModel) {
        Issuer issuer = Issuer.findIssuer(id);
        issuer.remove();
        uiModel.asMap().clear();
        uiModel.addAttribute("page", (page == null) ? "1" : page.toString());
        uiModel.addAttribute("size", (size == null) ? "10" : size.toString());
        return "redirect:/issuers";
    }
    
    void IssuerController.populateEditForm(Model uiModel, Issuer issuer) {
        uiModel.addAttribute("issuer", issuer);
    }
    
    String IssuerController.encodeUrlPathSegment(String pathSegment, HttpServletRequest httpServletRequest) {
        String enc = httpServletRequest.getCharacterEncoding();
        if (enc == null) {
            enc = WebUtils.DEFAULT_CHARACTER_ENCODING;
        }
        try {
            pathSegment = UriUtils.encodePathSegment(pathSegment, enc);
        } catch (UnsupportedEncodingException uee) {}
        return pathSegment;
    }
    
}
