// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.azotov.roo.web;

import com.azotov.roo.model.IssuerAgent;
import com.azotov.roo.web.IssuerAgentController;
import java.util.List;
import org.springframework.http.HttpHeaders;
import org.springframework.http.HttpStatus;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.ResponseBody;
import org.springframework.web.util.UriComponentsBuilder;

privileged aspect IssuerAgentController_Roo_Controller_Json {
    
    @RequestMapping(value = "/{id}", method = RequestMethod.GET, headers = "Accept=application/json")
    @ResponseBody
    public ResponseEntity<String> IssuerAgentController.showJson(@PathVariable("id") Long id) {
        IssuerAgent issuerAgent = IssuerAgent.findIssuerAgent(id);
        HttpHeaders headers = new HttpHeaders();
        headers.add("Content-Type", "application/json; charset=utf-8");
        if (issuerAgent == null) {
            return new ResponseEntity<String>(headers, HttpStatus.NOT_FOUND);
        }
        return new ResponseEntity<String>(issuerAgent.toJson(), headers, HttpStatus.OK);
    }
    
    @RequestMapping(headers = "Accept=application/json")
    @ResponseBody
    public ResponseEntity<String> IssuerAgentController.listJson() {
        HttpHeaders headers = new HttpHeaders();
        headers.add("Content-Type", "application/json; charset=utf-8");
        List<IssuerAgent> result = IssuerAgent.findAllIssuerAgents();
        return new ResponseEntity<String>(IssuerAgent.toJsonArray(result), headers, HttpStatus.OK);
    }
    
    @RequestMapping(method = RequestMethod.POST, headers = "Accept=application/json")
    public ResponseEntity<String> IssuerAgentController.createFromJson(@RequestBody String json, UriComponentsBuilder uriBuilder) {
        IssuerAgent issuerAgent = IssuerAgent.fromJsonToIssuerAgent(json);
        issuerAgent.persist();
        HttpHeaders headers = new HttpHeaders();
        headers.add("Content-Type", "application/json");
        RequestMapping a = (RequestMapping) getClass().getAnnotation(RequestMapping.class);
        headers.add("Location",uriBuilder.path(a.value()[0]+"/"+issuerAgent.getId().toString()).build().toUriString());
        return new ResponseEntity<String>(headers, HttpStatus.CREATED);
    }
    
    @RequestMapping(value = "/jsonArray", method = RequestMethod.POST, headers = "Accept=application/json")
    public ResponseEntity<String> IssuerAgentController.createFromJsonArray(@RequestBody String json) {
        for (IssuerAgent issuerAgent: IssuerAgent.fromJsonArrayToIssuerAgents(json)) {
            issuerAgent.persist();
        }
        HttpHeaders headers = new HttpHeaders();
        headers.add("Content-Type", "application/json");
        return new ResponseEntity<String>(headers, HttpStatus.CREATED);
    }
    
    @RequestMapping(value = "/{id}", method = RequestMethod.PUT, headers = "Accept=application/json")
    public ResponseEntity<String> IssuerAgentController.updateFromJson(@RequestBody String json, @PathVariable("id") Long id) {
        HttpHeaders headers = new HttpHeaders();
        headers.add("Content-Type", "application/json");
        IssuerAgent issuerAgent = IssuerAgent.fromJsonToIssuerAgent(json);
        issuerAgent.setId(id);
        if (issuerAgent.merge() == null) {
            return new ResponseEntity<String>(headers, HttpStatus.NOT_FOUND);
        }
        return new ResponseEntity<String>(headers, HttpStatus.OK);
    }
    
    @RequestMapping(value = "/{id}", method = RequestMethod.DELETE, headers = "Accept=application/json")
    public ResponseEntity<String> IssuerAgentController.deleteFromJson(@PathVariable("id") Long id) {
        IssuerAgent issuerAgent = IssuerAgent.findIssuerAgent(id);
        HttpHeaders headers = new HttpHeaders();
        headers.add("Content-Type", "application/json");
        if (issuerAgent == null) {
            return new ResponseEntity<String>(headers, HttpStatus.NOT_FOUND);
        }
        issuerAgent.remove();
        return new ResponseEntity<String>(headers, HttpStatus.OK);
    }
    
}
